#!/usr/bin/env bash
set -euo pipefail

# Materialize file-backed secrets from host-owned env files without sourcing or
# evaluating them. The generated container/service env files contain only
# non-secret settings and *_FILE paths.

PREFIX="${1:-/opt/sunaq}"
RUNTIME_ENV="$PREFIX/runtime.env"
PROVIDER_ENV="$PREFIX/provider.env"
SECRET_DIR="$PREFIX/runtime/service-secrets"
CONTAINER_ENV="$PREFIX/runtime.container.env"
SERVICE_ENV="$PREFIX/runtime.service.env"

[[ -f "$RUNTIME_ENV" ]] || { echo "runtime.env not found: $RUNTIME_ENV" >&2; exit 1; }

owner="$(stat -c '%u:%g' "$PREFIX/runtime" 2>/dev/null || true)"
[[ -n "$owner" ]] || owner="$(stat -c '%u:%g' "$PREFIX" 2>/dev/null || echo 0:0)"

container_tmp="$(mktemp)"
service_tmp="$(mktemp)"
new_secret_dir="$(mktemp -d "$PREFIX/runtime/.service-secrets.XXXXXX")"
old_secret_dir=""
cleanup() {
  local rc=$?
  set +e
  rm -f "$container_tmp" "$service_tmp"
  if [[ -n "$new_secret_dir" && -d "$new_secret_dir" ]]; then
    rm -rf "$new_secret_dir"
  fi
  if [[ -n "$old_secret_dir" && -d "$old_secret_dir" ]]; then
    rm -rf "$old_secret_dir"
  fi
  exit "$rc"
}
trap cleanup EXIT

chmod 700 "$new_secret_dir"
chown "$owner" "$new_secret_dir"

is_secret_key() {
  case "$1" in
    RAG_INTERNAL_API_KEY|RAG_PROVIDER_INTERNAL_KEY|RAG_CREDENTIAL_MASTER_KEY) return 0 ;;
    *_API_KEY|*_KEY|*_PASSWORD|*_TOKEN|*_SECRET|*_CREDENTIALS|*_AUTH_CONFIG) return 0 ;;
    *) return 1 ;;
  esac
}

is_runtime_non_secret_key() {
  case "$1" in
    RAG_ADMIN_USER|RAG_MAINTENANCE_MODE|RAG_CREDENTIAL_ENCRYPTION) return 0 ;;
    *) return 1 ;;
  esac
}

# Return the raw value from the final exact KEY= assignment. Exit 1 when the key
# is absent, which deliberately distinguishes "absent" from "present but empty".
read_last_raw() {
  local file="$1" key="$2" line="" found=1
  [[ -f "$file" ]] || return 1
  while IFS= read -r candidate || [[ -n "${candidate:-}" ]]; do
    case "$candidate" in
      "$key="*)
        line="${candidate#*=}"
        found=0
        ;;
    esac
  done < "$file"
  [[ $found -eq 0 ]] || return 1
  printf '%s' "$line"
}

# Decode the quoting used by ordinary dotenv/env_file assignments as data. Do
# not eval/source secret values.
decode_env_value() {
  local raw="$1"
  raw="${raw%$'\r'}"
  if [[ ${#raw} -ge 2 && "${raw:0:1}" == "'" && "${raw: -1}" == "'" ]]; then
    printf '%s' "${raw:1:${#raw}-2}"
    return
  fi
  if [[ ${#raw} -ge 2 && "${raw:0:1}" == '"' && "${raw: -1}" == '"' ]]; then
    raw="${raw:1:${#raw}-2}"
    raw="${raw//\\\"/\"}"
    raw="${raw//\\\\/\\}"
    printf '%s' "$raw"
    return
  fi
  printf '%s' "$raw"
}

read_effective_value() {
  local key="$1" raw value=""
  if raw="$(read_last_raw "$PROVIDER_ENV" "$key")"; then
    value="$(decode_env_value "$raw")"
  fi
  # runtime.env has precedence even when the explicit value is empty.
  if raw="$(read_last_raw "$RUNTIME_ENV" "$key")"; then
    value="$(decode_env_value "$raw")"
  fi
  printf '%s' "$value"
}

cat > "$container_tmp" <<'ENV'
# Generated by install/sync-container-secrets.sh.
# Contains no secret values; safe to use as a container env_file.
ENV
cat > "$service_tmp" <<'ENV'
# Generated by install/sync-container-secrets.sh.
# Contains no secret values; safe to source from native launch scripts.
ENV

# Preserve all non-secret compatibility settings without sourcing the input
# files. provider.env is applied first; runtime.env overrides duplicate keys.
copy_non_secret_env() {
  local file="$1" line key raw value
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "${line:-}" ]]; do
    [[ -n "$line" ]] || continue
    case "$line" in \#*) continue ;; esac
    [[ "$line" == *=* ]] || continue
    key="${line%%=*}"
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    [[ "$key" == "RAG_CREDENTIAL_MASTER_KEY_FILE" ]] && continue
    if is_secret_key "$key"; then
      continue
    fi
    if [[ "$key" == *_FILE ]] && is_secret_key "${key%_FILE}"; then
      continue
    fi
    # runtime.env is credential-bearing. Only documented non-secret controls
    # may be copied into process/container environments; every other runtime
    # key is materialized as a file-backed secret below.
    if [[ "$file" == "$RUNTIME_ENV" ]] && ! is_runtime_non_secret_key "$key"; then
      continue
    fi

    raw="${line#*=}"
    # Docker/Compose already understands dotenv quoting; retain it verbatim.
    printf '%s\n' "$line" >> "$container_tmp"

    # Native launch scripts source runtime.service.env. Re-emit decoded values
    # using shell-safe %q instead of copying executable shell syntax.
    value="$(decode_env_value "$raw")"
    printf '%s=%q\n' "$key" "$value" >> "$service_tmp"
  done < "$file"
}
copy_non_secret_env "$PROVIDER_ENV"
copy_non_secret_env "$RUNTIME_ENV"

# Credential-store master key already has its own dedicated root-managed file.
printf '%s=%s\n' RAG_CREDENTIAL_MASTER_KEY_FILE /app/runtime/credential-master.key >> "$container_tmp"
credential_key="$PREFIX/runtime/credential-master.key"
if raw="$(read_last_raw "$RUNTIME_ENV" RAG_CREDENTIAL_MASTER_KEY_FILE)"; then
  configured="$(decode_env_value "$raw")"
  [[ -n "$configured" ]] && credential_key="$configured"
fi
printf '%s=%q\n' RAG_CREDENTIAL_MASTER_KEY_FILE "$credential_key" >> "$service_tmp"

# Discover secret keys from both compatibility files. Keep explicit internal
# machine credentials in the canonical set because they do not match *_API_KEY.
declare -A secret_names=()
for file in "$PROVIDER_ENV" "$RUNTIME_ENV"; do
  [[ -f "$file" ]] || continue
  while IFS= read -r line || [[ -n "${line:-}" ]]; do
    [[ "$line" == *=* ]] || continue
    key="${line%%=*}"
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    if [[ "$file" == "$RUNTIME_ENV" ]]; then
      [[ "$key" == "RAG_CREDENTIAL_MASTER_KEY_FILE" ]] && continue
      is_runtime_non_secret_key "$key" && continue
      # Fail closed for administrator-defined api_key_env names: runtime.env is
      # the documented credential file, so unknown keys are secrets by default.
      secret_names["$key"]=1
      continue
    fi
    is_secret_key "$key" || continue
    secret_names["$key"]=1
  done < "$file"
done

for key in "${!secret_names[@]}"; do
  value="$(read_effective_value "$key")"
  target="$new_secret_dir/$key"
  printf '%s' "$value" > "$target"
  chmod 600 "$target"
  chown "$owner" "$target"
  printf '%s_FILE=/run/sunaq-secrets/%s\n' "$key" "$key" >> "$container_tmp"
  printf '%s_FILE=%q\n' "$key" "$SECRET_DIR/$key" >> "$service_tmp"
done

# Neo4j supports NEO4J_AUTH_FILE, whose file contains user/password together.
if [[ -n "${secret_names[NEO4J_PASSWORD]+x}" ]]; then
  neo4j_password="$(read_effective_value NEO4J_PASSWORD)"
  printf 'neo4j/%s' "$neo4j_password" > "$new_secret_dir/neo4j_auth"
  # Container uid may differ from the SunaQ service uid.
  chmod 0444 "$new_secret_dir/neo4j_auth"
  chown "$owner" "$new_secret_dir/neo4j_auth"
fi

# Replace the complete known secret directory so rotation/removal cannot leave
# stale files behind. Callers restart affected services after synchronization.
if [[ -d "$SECRET_DIR" ]]; then
  old_secret_dir="$PREFIX/runtime/.service-secrets.old.$$"
  rm -rf "$old_secret_dir"
  mv "$SECRET_DIR" "$old_secret_dir"
fi
mv "$new_secret_dir" "$SECRET_DIR"
new_secret_dir=""
rm -rf "$old_secret_dir"
old_secret_dir=""

install -m 0640 "$container_tmp" "$CONTAINER_ENV"
install -m 0640 "$service_tmp" "$SERVICE_ENV"
chown "$owner" "$CONTAINER_ENV" "$SERVICE_ENV"

echo "File-backed runtime secrets synchronized: $SECRET_DIR"
